<a href="https://colab.research.google.com/github/aarontgao2023/B529/blob/main/529_assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# B529 Machine Learning in Bioinformatics: Assignment 1

---


# Question 1


$$\begin{array}{ll}\mathbf{x}_1=(1,2,0)^{\top} & y_1=+1 \\ \mathbf{x}_2=(1,2,2)^{\top} & y_2=+1 \\ \mathbf{x}_3=(1,0,2)^{\top} & y_3=-1\end{array}$$
$$ w_0 = \begin{bmatrix}0 & 6 & 6\end{bmatrix}$$
**Iteration 1:**  
$\operatorname{sign}(\mathbf{w_0}^{\mathrm{T}} \mathbf{x_1}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 0\end{bmatrix} \begin{bmatrix}0 \\ 6 \\ 6\end{bmatrix}) = \operatorname{sign}(12) = +1 = y_1$

$\operatorname{sign}(\mathbf{w_0}^{\mathrm{T}} \mathbf{x_2}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 2\end{bmatrix} \begin{bmatrix}0 \\ 6 \\ 6\end{bmatrix}) = \operatorname{sign}(24) = +1 = y_2$

$\operatorname{sign}(\mathbf{w_0}^{\mathrm{T}} \mathbf{x_3}) =
\operatorname{sign}(\begin{bmatrix}1 & 0 & 2\end{bmatrix} \begin{bmatrix}0 \\ 6 \\ 6\end{bmatrix}) = \operatorname{sign}(12) = +1 \neq y_3$

$w_1 = w_0+ y_3 * x3 = \begin{bmatrix}-1 & 6 & 4\end{bmatrix}$

**Iteration 2:**  
$\operatorname{sign}(\mathbf{w_1}^{\mathrm{T}} \mathbf{x_1}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 0\end{bmatrix} \begin{bmatrix}-1 \\ 6 \\ 4\end{bmatrix}) = \operatorname{sign}(11) = +1 = y_1$

$\operatorname{sign}(\mathbf{w_1}^{\mathrm{T}} \mathbf{x_2}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 2\end{bmatrix} \begin{bmatrix}-1 \\ 6 \\ 4\end{bmatrix}) = \operatorname{sign}(19) = +1 = y_2$

$\operatorname{sign}(\mathbf{w_1}^{\mathrm{T}} \mathbf{x_3}) =
\operatorname{sign}(\begin{bmatrix}1 & 0 & 2\end{bmatrix} \begin{bmatrix}-1 \\ 6 \\ 4\end{bmatrix}) = \operatorname{sign}(7) = +1 \neq y_3$

$w_2 = w_1+ y_3 * x3 = \begin{bmatrix}-2 & 6 & 2\end{bmatrix}$

**Iteration 3:**  
$\operatorname{sign}(\mathbf{w_2}^{\mathrm{T}} \mathbf{x_1}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 0\end{bmatrix} \begin{bmatrix}-2 \\ 6 \\ 2\end{bmatrix}) = \operatorname{sign}(10) = +1 = y_1$

$\operatorname{sign}(\mathbf{w_2}^{\mathrm{T}} \mathbf{x_2}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 2\end{bmatrix} \begin{bmatrix}-2 \\ 6 \\ 2\end{bmatrix}) = \operatorname{sign}(14) = +1 = y_2$

$\operatorname{sign}(\mathbf{w_2}^{\mathrm{T}} \mathbf{x_3}) =
\operatorname{sign}(\begin{bmatrix}1 & 0 & 2\end{bmatrix} \begin{bmatrix}-2 \\ 6 \\ 2\end{bmatrix}) = \operatorname{sign}(2) = +1 \neq y_3$

$w_3 = w_2+ y_3 * x3 = \begin{bmatrix}-3 & 6 & 0\end{bmatrix}$

**Iteration 4:**  
$\operatorname{sign}(\mathbf{w_3}^{\mathrm{T}} \mathbf{x_1}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 0\end{bmatrix} \begin{bmatrix}-3 \\ 6 \\ 0\end{bmatrix}) = \operatorname{sign}(9) = +1 = y_1$

$\operatorname{sign}(\mathbf{w_3}^{\mathrm{T}} \mathbf{x_2}) =
\operatorname{sign}(\begin{bmatrix}1 & 2 & 2\end{bmatrix} \begin{bmatrix}-3 \\ 6 \\ 0\end{bmatrix}) = \operatorname{sign}(9) = +1 = y_2$

$\operatorname{sign}(\mathbf{w_3}^{\mathrm{T}} \mathbf{x_3}) =
\operatorname{sign}(\begin{bmatrix}1 & 0 & 2\end{bmatrix} \begin{bmatrix}-3 \\ 6 \\ 0\end{bmatrix}) = \operatorname{sign}(-3) = +1 = y_3$

$w_3$ have all points correctly classified, therefore weight vector $w = \begin{bmatrix}-3 & 6 & 0\end{bmatrix}$

In [ ]:
import numpy as np
def perceptron_step(w, x, y):
    y_pred = np.sign(np.dot(w, x))
    if y_pred != y:
        w = w + y * x
    return w

w = np.array([0, 6, 6])
data_points = [
    (np.array([1, 2, 0]), 1),
    (np.array([1, 2, 2]), 1),
    (np.array([1, 0, 2]), -1)
]

converged = False
iterations = 0
while not converged:
    iterations += 1
    converged = True
    for x, y in data_points:
        w_old = w.copy()
        w = perceptron_step(w, x, y)
        if not np.array_equal(w, w_old):
            converged = False
print(f"Final weight vector: {w}")

Final weight vector: [-3  6  0]




---



# Question 2

## (a)

In [ ]:
X = np.array([[1, 3, 2],[1, 2, 2],[1, 1, -1],[1, -1, -3]])
#X = np.matrix("1,3,2;1,2,2;1,1,-1;1,-1,-3")
y = np.array([3, 1, -1, -3])
from numpy.linalg import inv
w = inv(X.T @ X) @ X.T @ y
w

array([-1.66666667,  1.33333333,  0.11111111])

## (b)

In [ ]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression(fit_intercept=False).fit(X, y)
w = reg.coef_
w

array([-1.66666667,  1.33333333,  0.11111111])



---



# Question 3

## Input data

In [9]:
import numpy as np
class1 = np.matrix([[4, 3], [2, 2]])
class2 = np.matrix([[1, 1], [-2, -1]])
y1 = 1
y2 = 1
y3 = -1
y4 = -1

##  Mean vectors

In [10]:
mean1 = np.mean(class1, axis=0)
mean2 = np.mean(class2, axis=0)
mean1

matrix([[3. , 2.5]])

## Within-class scatter matrix

In [5]:
S_W = np.zeros((2,2))
for x in class1:
    x = x.reshape(2,1)
    m = mean1.reshape(2,1)
    S_W += (x - m).dot((x - m).T)
for x in class2:
    x = x.reshape(2,1)
    m = mean2.reshape(2,1)
    S_W += (x - m).dot((x - m).T)
S_W

array([[6.5, 4. ],
       [4. , 2.5]])

## w

In [11]:
from numpy.linalg import inv
W = inv(S_W) * (mean2.transpose() - mean1.transpose())
W

matrix([[ 5.],
        [-9.]])



---



# Question 4

 ## Load package and the dataset

In [ ]:
from sklearn.linear_model import Perceptron
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import pandas as pd

heart_disease_data = pd.read_csv('/content/drive/MyDrive/529_HW/heart_disease_data.txt')
heart_disease_data.head()

age  sex   cp  trestbps   chol  fbs  restecg  thalach  exang  oldpeak  \
0  63.0  1.0  1.0     145.0  233.0  1.0      2.0    150.0    0.0      2.3   
1  67.0  1.0  4.0     160.0  286.0  0.0      2.0    108.0    1.0      1.5   
2  67.0  1.0  4.0     120.0  229.0  0.0      2.0    129.0    1.0      2.6   
3  37.0  1.0  3.0     130.0  250.0  0.0      0.0    187.0    0.0      3.5   
4  41.0  0.0  2.0     130.0  204.0  0.0      2.0    172.0    0.0      1.4   

   slope   ca  thal  num  
0    3.0  0.0   6.0    0  
1    2.0  3.0   3.0    1  
2    2.0  2.0   7.0    1  
3    3.0  0.0   3.0    0  
4    1.0  0.0   3.0    0

## Preparation

In [ ]:
X = heart_disease_data.drop('num', axis=1)  # Features
y = heart_disease_data['num']  # Target variable

## Perception

In [ ]:
perceptron = Perceptron()
perceptron.fit(X, y)
w_perceptron = perceptron.coef_
w_perceptron

array([[  731. ,    67. ,   197. ,   325. ,    23. ,   -10. ,   116. ,
        -1187. ,    59. ,   189.9,    93. ,   159. ,   508. ]])

## LDA

In [ ]:
lda = LinearDiscriminantAnalysis()
lda.fit(X, y)
w_lda = lda.coef_
w_lda

array([[-0.00473584,  1.26780721,  1.30117132, -0.03437771,  0.01697281,
        -0.07954438,  0.66800376, -0.01986038,  0.32713953,  0.78643444,
         0.25465599,  1.02247583,  0.99167057]])